"""Create DB

Revision ID: 942641c61bc1
Revises: 
Create Date: 2019-12-20 15:34:20.939786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942641c61bc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snippet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('snippet', sa.String(length=1000000), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snippet_name'), 'snippet', ['name'], unique=True)
    op.create_index(op.f('ix_snippet_snippet'), 'snippet', ['snippet'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snippet_snippet'), table_name='snippet')
    op.drop_index(op.f('ix_snippet_name'), table_name='snippet')
    op.drop_table('snippet')
    # ### end Alembic commands ###
